#
# rose_freeze - the main 'ROSA Freeze' module
#
# Author: Denis Silakov <denis.silakov@rosalab.ru>
#
# Copyright (C) 2014-2015 ROSA Company
#
# Distributed under the BSD license
#

import argparse
import os
import re
import sys
import shutil
import time
import subprocess
import fileinput

grub_cfg_name = '/etc/default/grub'

rfreeze_config = '/etc/rfreeze.conf'
modulename = 'overlay'

#########################
# Top-level functions:
#   * enable_freeze
#   * disable_freeze
#   * get_status
#########################

'''
Enable freeze mode

Return Value:
    0 - success
    2 - freeze mode is already enabled
    3 - freeze mode was disabled but the system was not rebooted after that
    4 - failed to get UUID for the storage device
    5 - storage device is already mounted
    61 - path to the folder is not absolute
    62 - can't determine top-level parent for the folder
    99 - smth went wrong during 'os.system' run
'''
def enable_freeze(skip_dirs, storage, folder=""):
    status = get_status()
    if status == 'enabled':
        return 2
    elif status == 'disabled_pending':
        return 3

    uuid = ""

    # Disable systemd service for now, it is not well tested yet.
    use_systemd = 0
    # Enable service responsible for freezing non-root partitions
#    if os.system("systemctl enable rosa-freeze") != 0:
#        use_systemd = 0

    # Detect folders that are mount points for other partitions
    # NOTE: only currently mounted partitions will be taken into account
    # If we don't have systemd (in RELS 6) then currently we will just skip these folders
    more_dirs = _folders_from_other_partitions(skip_dirs, use_systemd)
    if use_systemd:
        rfreeze_partitions_conf = open('/etc/sysconfig/rfreeze', 'w')
        rfreeze_partitions_conf.write("# List of folders to be frozen that are mount points for non-root partitions.\n")
        rfreeze_partitions_conf.write("# Space separated, without leading slashes.\n\n")
        rfreeze_partitions_conf.write("# This file is automatically generated by rfreeze.\n")
        rfreeze_partitions_conf.write("OUTER_FOLDERS=\"" + " ".join(more_dirs) + "\"\n")
    else:
        skip_dirs.extend(more_dirs)

    if storage == "folder":
        if not folder.startswith("/"):
            return 61

        if not os.path.exists(folder):
            if os.system("mkdir -p " + folder):
                return 99

        # Let's ensure that the folder will not be frozen
        path_components = folder.split("/")
        if not path_components[1]:
            # Can't determine top-level parent for the folder
            return 62

        if not path_components[1] in skip_dirs:
            skip_dirs.append(path_components[1])

    elif storage != "tmpfs":
        # Separate partition will be used as a storage
	uuid = _get_device_uuid(storage)
	if not uuid:
	    return 4
	storage_mnt = os.popen("findmnt -n -o TARGET " + storage).read().rstrip()
	if storage_mnt:
	    return 5

    # For safety - load module
    if os.system("modprobe " + modulename):
        return 99

    # Enable filesystem mounting for root in dracut
    _enable_freeze_dracut(uuid, skip_dirs, folder)

    # Make sure that kernel module is loaded at boot time
    if not os.path.isfile('/etc/modules-load.d/' + modulename + '.conf'):
        union_conf = open('/etc/modules-load.d/' + modulename + '.conf', 'w')
        union_conf.write(modulename + '\n')
        union_conf.close()

    # Finally, let's enter freeze mode right now
    _enable_freeze_now(skip_dirs, storage, folder, use_systemd)

    return 0

'''
Disable freeze mode

Return Value:
    0 - success
    1 - freeze mode is not enabled
'''
def disable_freeze():
    status = get_status()
    if status != 'enabled':
        return 1

    # Disable service responsible for freezing non-root partitions
    # For the case when we don't have systemd (RELS 6), just ignore the errors
    os.system("systemctl disable rosa-freeze")

    # Find original root folder and mount it to /tmp/sysroot-orig
    #orig_root = os.popen("findmnt -n -o SOURCE --target /tmp/sysroot-ro").read().rstrip()
    os.system("mkdir -p /tmp/sysroot-orig")
    #os.system("mount -o rw " + orig_root + " /tmp/sysroot-orig")
    os.system("mount -o bind / /tmp/sysroot-orig")
    # Prepare for chrooting into sysroot-orig
    os.system("mount -o bind /dev /tmp/sysroot-orig/dev")
    os.system("mount -o bind /dev/pts /tmp/sysroot-orig/dev/pts")
    os.system("mount -o bind /proc /tmp/sysroot-orig/proc")
    os.system("mount -o bind /sys /tmp/sysroot-orig/sys")
    os.system("mount -o bind /run /tmp/sysroot-orig/run")
    os.system("mount -o bind /boot /tmp/sysroot-orig/boot")
    # Update dracut options in grub config
    _disable_freeze_dracut('/tmp/sysroot-orig/')
    os.system("chroot /tmp/sysroot-orig/ update-grub2")

    # Cleanup
#    os.system("umount /tmp/sysroot-orig")
#    os.system("rm -f /tmp/sysroot-orig")

    return 0

'''
Try to merge current state to the original filesystem

Parameters:
    backup_folder - if not empty, specifies a fodler to store backups of modified/removed files

Return Value:
    0 - success
    1 - freeze mode is not enabled
    99 - smth went wrong during os.system run
'''
def merge_state(backup_folder="",skip_dirs="workdir"):
    status = get_status()
    if status != 'enabled':
        return 1

    # Find original root device and mount it to /tmp/sysroot-orig
    #orig_root = os.popen("findmnt -n -o SOURCE --target /tmp/sysroot-ro").read().rstrip()

    if os.system("mkdir -p /tmp/sysroot-orig"):
        return 99
    #if os.system("mount -o rw " + orig_root + " /tmp/sysroot-orig"):
    if os.system("mount -o bind / /tmp/sysroot-orig"):
        return 99

    backup_params = ""
    if backup_folder > "":
        backup_params = "--backup --backup-dir=" + backup_folder

    # rsync current state of 'frozen' folders.
    # Note that we don't support situation when some of these folders
    # are originally mounted from different partitions
    # (e.g., /var on separate partinion is not supported)
    for d in os.listdir('/tmp/sysroot-rw/'):
        if os.path.isdir("/tmp/sysroot-rw/" + d) and d not in skip_dirs:
	    if os.system("rsync -avH --delete " + backup_params + " /" + d + " /tmp/sysroot-orig"):
		return 99

    # Cleanup
#    os.system("umount /tmp/sysroot-orig")
#    os.system("rm -f /tmp/sysroot-orig")

    return 0

'''
Get current status of ROSA Freeze

Possible return values:
    * 'enabled'
    * 'disabled'
    * 'disabled_pending' (freeze mode was disabled, but the system was not rebooted after that)
'''
def get_status():
    union_enabled = os.system("grep GRUB_CMDLINE_LINUX " + grub_cfg_name + " | grep -q " + modulename + "_root")
    if os.path.isdir("/tmp/sysroot-rw"):
        union_mounted = os.system("findmnt --target /tmp/sysroot-rw -n | grep -v /dev/mapper > /dev/null")
    else:
        union_mounted = 1
    if union_enabled == 0 and union_mounted == 0:
        return 'enabled'
    else:
        if union_mounted == 0:
            return 'disabled_pending'
        else:
            return 'disabled'

'''
Create restore point

Return Value:
    0 - success
    1 - freeze mode is not enabled
    2 - no folder is specified to store restore point and tmpfs is used to store changes;
        we refuse to create restore points in tmpfs
'''
def create_restore_point(folder=""):
    status = get_status()
    if status != 'enabled':
        return 1

    storage_type = os.popen("findmnt -n -o SOURCE --target /tmp/sysroot-rw").read().rstrip()
    if storage_type == "tmpfs":
        return 2

    if folder == "":
        folder = "/tmp/sysroot-orig/restore_points"
    else:
	folder = "/tmp/sysroot-orig" + folder

    # Append current timestamp to folder
    folder = folder + "/" + str(int(time.time()))

    res = merge_state(folder)
    exit(res)

'''
Get available restore points
'''
def list_restore_points(folder=""):
    points = []
    try:
        points = [d for d in os.listdir(folder) if os.path.isdir(folder + "/" + d)]
    except:
        # Just return empty array if we can't get a list of restore points
        # (e.g., if 'folder' doesn't exist or can't be read)
        pass

    return points

'''
Clean given (or all) restore points
'''
def clean_restore_points(folder, last_date=None):
    for d in os.listdir(folder):
	if last_date is None or int(d) <= last_date:
    	    shutil.rmtree(folder + "/" + d)


'''
Rollback to a given restore point

Parameters:
    folder - a fodler with backups of modified/removed files

Return Value:
    0 - success
    1 - invalid restore point
    99 - smth went wrong during os.system run
'''
def rollback_to_point(point, folder=""):
    points = list_restore_points(folder)
    if point not in points:
        return 1

    for d in os.listdir(folder + '/' + point):
        if os.system("rsync -avH --delete " + folder + "/" + point + "/" + d + " /" + d):
            return 99

    return 0


###########################
# Interlal functions
###########################

'''
Modify dracut parameters in grub config - drop root
'''
def _disable_freeze_dracut(chroot=""):
    try:
        # /etc is protected
        grub_cfg = open(chroot + grub_cfg_name, 'r')
        grub_new_cfg = open(chroot + grub_tmp_cfg_name, 'w')
    except:
        # /etc is skipped
        grub_cfg = open(grub_cfg_name, 'r')
        grub_new_cfg = open(grub_tmp_cfg_name, 'w')

    for line in grub_cfg:
        if line.startswith('GRUB_CMDLINE_LINUX'):
            line = re.sub(r'%s_root=UUID=[\S]*([\'" ])' % modulename, r'\1', line)
            line = re.sub(r'%s_root=DIR=[\S]*([\'" ])' % modulename, r'\1', line)
            line = re.sub(r' rfreeze_skip_dirs=[\S]*([\'" ])', r'\1', line)
        grub_new_cfg.write(line)
    grub_new_cfg.close()

    try:
        # /etc is protected
        shutil.move(chroot + grub_tmp_cfg_name, chroot + grub_cfg_name)
    except:
        # /etc is skipped
        shutil.move(grub_tmp_cfg_name, grub_cfg_name)


'''
Enter freeze mode in a running system
'''
def _enable_freeze_now(skip_dirs, storage, folder="", use_systemd=1):
    os.system("mkdir -p /tmp/xinos")
    os.system("mkdir -p /tmp/sysroot-rw")
    #os.system("mkdir -p /tmp/sysroot-ro")
    #os.system("mount -o bind / /tmp/sysroot-ro")
    if storage == "tmpfs" or storage == "folder":
	os.system("mount -n -t tmpfs tmpfs /tmp/sysroot-rw")
    else:
	os.system("mount -n " + storage + " /tmp/sysroot-rw")

    for d in os.listdir('/'):
        if os.path.isdir("/" + d) and d not in skip_dirs:
            os.system("rm -rf /tmp/sysroot-rw/" + d)
            if d == "root":
                os.system("mkdir -m 750 -p /tmp/sysroot-rw/" + d)
            else:
                os.system("mkdir -m 755 -p /tmp/sysroot-rw/" + d)

	    if modulename == 'aufs':
            	if os.system("mount -n -t aufs -o nowarn_perm,noatime,xino=/tmp/xinos/" + d + ".xino.aufs,dirs=/tmp/sysroot-rw/" + d + "=rw:/" + d + "=rr none /" + d):
                    return 99
	    elif modulename == 'overlay':
	    	if os.system("mkdir -p /tmp/sysroot-rw/workdir/" + d + "; mount -n -t overlay -o upperdir=/tmp/sysroot-rw/" + d + ",lowerdir=/" + d + ",workdir=/tmp/sysroot-rw/workdir/" + d + " none /" + d):
                    return 99

    if use_systemd:
        os.system("systemctl start rosa-freeze")

'''
Modify dracut parameters in grub config - add root
'''
def _enable_freeze_dracut(uuid, skip_dirs, folder):
    dracut_skip_dirs = ":".join(skip_dirs)

    # Check if initrd already contains union-mount
    # Commented out line which doesn't work in RELS 6 with py26
#    lsinitrd = subprocess.check_output(('lsinitrd'))
    lsinitrd = subprocess.Popen(['lsinitrd'], stdout=subprocess.PIPE).communicate()[0]
    union_mount_present = lsinitrd.find("union_mount") >= 0
    if not union_mount_present:
        os.system('dracut -f /boot/initrd-$(uname -r).img $(uname -r)')

    grub_cfg = fileinput.FileInput(grub_cfg_name, inplace=True)
    for line in grub_cfg:
        if line.startswith('GRUB_CMDLINE_LINUX'):
            line = re.sub(r'([\'"]\s*)$', r' rfreeze_skip_dirs=%s %s_root=UUID=\1' % (dracut_skip_dirs,modulename), line)
            if uuid:
                line = line.replace(modulename + "_root=UUID=",modulename +  "_root=UUID=" + uuid)
            elif folder:
                line = line.replace(modulename + "_root=UUID=", modulename +  "_root=DIR=" + folder)
        print(line.rstrip())

    os.system("update-grub2")

'''
Get UUID by device name
'''
def _get_device_uuid(storage):
    uuid = os.popen("blkid " + storage + " -o udev | grep 'UUID=' | cut -f2 -d=").read().rstrip()
    return uuid

'''
Detect which top-level folders are used as a mount points.
Return a list of such folders which are not yet included in skip_dirs
'''
def _folders_from_other_partitions(skip_dirs, use_systemd):
    more_dirs = []
    for d in os.listdir('/'):
        if os.path.isdir("/" + d) and d not in skip_dirs:
            dir_mnt = os.popen("findmnt -n -o TARGET /" + d).read().rstrip()
            if dir_mnt:
                more_dirs.append(d)
                if not use_systemd:
                    print(_("NOTE: '%s' folder is mounted from another partition, it will not be frozen") % d)

    return more_dirs
